// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDopXN7E8BfSzz2MfTvSaBjmG1WCqj_lWo',
    appId: '1:76242713800:web:59640fbf5814b06c3ff9fd',
    messagingSenderId: '76242713800',
    projectId: 'committee-pay-app',
    authDomain: 'committee-pay-app.firebaseapp.com',
    storageBucket: 'committee-pay-app.firebasestorage.app',
    measurementId: 'G-2PMT0S2FRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpICC9ofXbg4c7lpF-ImulDMeeqpHC7yU',
    appId: '1:76242713800:android:7d857efbe8fee05e3ff9fd',
    messagingSenderId: '76242713800',
    projectId: 'committee-pay-app',
    storageBucket: 'committee-pay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlFl72tTKGBPlZzW-DssBXyBVjmE4rXo',
    appId: '1:76242713800:ios:e78b8b8c9e25316f3ff9fd',
    messagingSenderId: '76242713800',
    projectId: 'committee-pay-app',
    storageBucket: 'committee-pay-app.firebasestorage.app',
    iosBundleId: 'com.example.committeePayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMlFl72tTKGBPlZzW-DssBXyBVjmE4rXo',
    appId: '1:76242713800:ios:e78b8b8c9e25316f3ff9fd',
    messagingSenderId: '76242713800',
    projectId: 'committee-pay-app',
    storageBucket: 'committee-pay-app.firebasestorage.app',
    iosBundleId: 'com.example.committeePayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDopXN7E8BfSzz2MfTvSaBjmG1WCqj_lWo',
    appId: '1:76242713800:web:fd0d16d7dd35b0cc3ff9fd',
    messagingSenderId: '76242713800',
    projectId: 'committee-pay-app',
    authDomain: 'committee-pay-app.firebaseapp.com',
    storageBucket: 'committee-pay-app.firebasestorage.app',
    measurementId: 'G-BYTXMNLGHH',
  );
}
